### ISSUE TITLE
IMAP Proxy with nginx

### ISSUE THREAD

**Issue by frereit** [cirosec-studis/smtp-bridge#10]
The Docker Container should also expose a IMAP server so that the imap and smtp server are the same.

This is a low priority feature.

 [nginx example](https://www.nginx.com/resources/wiki/start/topics/examples/imapproxyexample/)

**Comment by JM-Lemmi** [comment]
Maybe even spin this into its own container. This simplifies the containers and allows using only one of the services, if the other is not needed

**Comment by frereit** [comment]
> Maybe even spin this into its own container. 

agreed.
